### ISSUE TITLE
Is This Figure Wrong?

### ISSUE THREAD

**Issue by Net-Maker** [Fictionarry/DNGaussian#1]
<img width="481" alt="image" src="https://github.com/Fictionarry/DNGaussian/assets/79513614/df23d30e-3d40-4ebe-aa37-b2ae783cd744">
 
I think the PSNR should be 29?

**Comment by Fictionarry** [comment]
Yeah, we have made a mistake here, the correct PSNRs should be **28.94**, 39.30, 30.66 for the input view.
In situations with sparse input views, it is reasonable for a higher PSNR than that of dense views due to overfitting.
Thanks for your checking! We'll correct it in the camera ready version.

**Comment by Net-Maker** [comment]
Wow, I thought the 39.30 is wrong at first.So it's a lucky misunderstanding :)
