### ISSUE TITLE
ModuleNotFoundError: No module named '_shencoder'

### ISSUE THREAD

**Issue by zhanghaoyu816** [Fictionarry/DNGaussian#10]
Hello, Thanks for this great work
I have encountered some problems when I run this code. There has a error in line31 of shencoder/backend.py
<img width="843" alt="image" src="https://github.com/Fictionarry/DNGaussian/assets/60644792/c6bf5452-6e17-46c7-a5b0-2a5ff0af7f57">
<img width="543" alt="image" src="https://github.com/Fictionarry/DNGaussian/assets/60644792/fe2be4a6-3d05-46ff-8cb7-f286d5f72f8c">

Actually, I have already installed Ninja, and I didn't meet problem in the installation of gridencoder
<img width="763" alt="image" src="https://github.com/Fictionarry/DNGaussian/assets/60644792/4b08265e-e968-4a71-a6fc-82f00da9c455">
<img width="545" alt="image" src="https://github.com/Fictionarry/DNGaussian/assets/60644792/6856ed47-bbce-4244-b337-2c8455067a02">

So could you please give some recommends to solve this problem? Thank you very much

**Comment by Fictionarry** [comment]
Hello, how about installing shencoder manually through `pip install ./shencoder`? I guess it may be helpful, considering the gridencoder module can be successfully installed through pip

**Comment by zhanghaoyu816** [comment]
Thanks a lot for your reply!  This problem has been successfully solved
