### ISSUE TITLE
Question about the self._depth_err attribute in GaussianModel

### ISSUE THREAD

**Issue by JiajieLi7012** [Fictionarry/DNGaussian#15]
Hello, I'm wondering why we need the optimizable attribute self._depth_err in the GaussianModel. Thanks in advance.

**Comment by Fictionarry** [comment]
Hi, these are the remaining codes of some tries which we have finally abandoned. You can just ignore it.

**Comment by JiajieLi7012** [comment]
I see. Thanks.
