### ISSUE TITLE
questions about neareset gaussians 

### ISSUE THREAD

**Issue by tb2-sy** [Fictionarry/DNGaussian#20]
Thanks for your work!
In the optimization of hard depth, the nearest gaussians closest to the camera are mentioned. How will the gaussians other than the nearest gaussians be processed? Will they always exist in the optimization process or will they be deleted in the subsequent densify process because the opacity is too low?

**Comment by Fictionarry** [comment]
Hi, in fact the nearest gaussians are mainly affected by the hard depth regularization, while the others can still be optimized by the color supervision (as in original 3DGS) and soft depth regularization, and so on.

**Comment by tb2-sy** [comment]
Thanks for your answer!
