### ISSUE TITLE
Use_sh in Train_blender.sh

### ISSUE THREAD

**Issue by Ballzy0706** [Fictionarry/DNGaussian#25]
Dear authors,

Thanks for your work!

I noticed that you are using the training_sh function when training Blender, but not for the DTU and LLFF datasets. Could you explain the difference between this function and the regular training function?

Best regards.

**Comment by Fictionarry** [comment]
Hi, the main difference is that train() uses the neural renderer to store the RGB color, while training_sh uses SHs like original 3DGS.  The neural renderer works for avoid the  overfitting in SHs in very sparse view situations (like 3 views in DTU and LLFF), just like explained in the paper. In the Blender setting with 8 training views , SH performs better than neural renderer at most times.

**Comment by Ballzy0706** [comment]
I see, thanks for the quick response!
