### ISSUE TITLE
need for qualitative results

### ISSUE THREAD

**Issue by Ballzy0706** [Fictionarry/DNGaussian#27]
Thanks for your great work!

Could you please provide the qualitative results of the experimental and comparative methods presented in your paper, as well as the code for evaluating rendering speed (FPS).

Looking forward to your response.

**Comment by Fictionarry** [comment]
Hi, you can get the generated results from our released checkpoints. The rendering speed is tested according to running `spiral.py`, where we additionally removed the image saving operations to be free from disk IO delays.

**Comment by Ballzy0706** [comment]
Thanks for your reply!
