### ISSUE TITLE
the results are bad

### ISSUE THREAD

**Issue by dyccyber** [Fictionarry/DNGaussian#28]
![00016](https://github.com/Fictionarry/DNGaussian/assets/129243050/612745c4-9f44-4739-b197-8ce83562a92c)
hi，i find the training results are not good ，using the default parameter setting, can you give me some advice on how to adjust the parameter

**Comment by Fictionarry** [comment]
Well, it's what exact the quality of this scene trained using only the sampled 8 views. In fact these sampled training views can not provide sufficient information to recover some regions. Here I provide a result from FreeNeRF for you as a reference. You can see that the bad areas are nearly the same (like the small drum on the left). 
![016](https://github.com/Fictionarry/DNGaussian/assets/45344906/ab1ac258-3ff8-4f69-a3cb-bfb8a2fe6d99)

**Comment by dyccyber** [comment]
thanks, i get it
