### ISSUE TITLE
Questions about test

### ISSUE THREAD

**Issue by Star-XingHe** [Fictionarry/DNGaussian#29]
I noticed that in metrics.py, the evaluation data is used to obtain quantitative results using only 3 pictures. Could you please explain why test data is not used for obtaining these results? For example, the "fern" has 17 pictures available for testing.

Thank you for your time and assistance.

**Comment by Fictionarry** [comment]
Hi, this setting is also used in previous works like RegNeRF, FreeNeRF and SparseNeRF. We use it to keep an alignment with previous methods in comparison. 

Additionally, the images divided into "test" are not the actual test data. They are the images neither used in training nor in evaluation. Thus I put them in the "test" division for convenience.
