### ISSUE TITLE
关于文中提到的 neareset gaussians 

### ISSUE THREAD

**Issue by zhangfang97** [Fictionarry/DNGaussian#5]
您好，我注意到文中有提到 depth regularization 时，主要针对的是 基于射线的 最近的高斯点，目的是期望促进这些近处的高斯的移动，也即：

we render a "hard depth" that mainly consists of the nearest Gaussians on the ray shot from camera center o and across the pixel

但我在代码的实现中似乎并没有看到根据相机位姿和pixel来提取 nearset Gaussians 这一步

我是否遗漏了哪些地方呢，又或者这种对于 nearest Gaussians 的约束，主要也是隐含在 depth 的loss里，并不需要额外的显式提取？

感谢您的帮助

**Comment by Fictionarry** [comment]
您好，我们通过在渲染hard depth时设置一个固定的大opacity值，以使得hard depth主要反映最近的Gaussians的距离，而较远处的点则将被近处具有大opacity的Gaussians遮挡住，因此优化时梯度几乎只会传播至这些nearest Gaussians

**Comment by zhangfang97** [comment]
我理解了，非常感谢！
