### ISSUE TITLE
Question about colmap on DTU dataset

### ISSUE THREAD

**Issue by kqjt0e11gy0jkgmy** [Fictionarry/DNGaussian#6]
Thanks for your fancy work~
Here I met some problems when re-producing your work on DTU dataset. Specifically, the colmap failed on the scan30, 63 and 82. Most of images showed "Could not register, trying another image" and I can only get maybe "Reconstruction with 2 images and 180 points"? Is that normal? or in which step did I make an error? It would be better if you can provide the colmap result of DTU dataset.
Thanks again and looking forward to your reply~

**Comment by Fictionarry** [comment]
Hi, I have just retried the preprocessing steps of DTU in environments of COLMAP 3.8, Windows 10 and COLMAP 3.6, Ubuntu 18, and didn't encounter these problems.  Could you please provide more details about where these problems occur?  Did they occur when running `convert.py` to handle all views in one scene, or in other situations else？

**Comment by kqjt0e11gy0jkgmy** [comment]
> Hi, I have just retried the preprocessing steps of DTU in environments of COLMAP 3.8, Windows 10 and COLMAP 3.6, Ubuntu 18, and didn't encounter these problems. Could you please provide more details about where these problems occur? Did they occur when running `convert.py` to handle all views in one scene, or in other situations else？

Thanks for replying~
My attempt is in the environment of COLMAP 3.9-dev, Ubuntu 22.04, and the problem occured when running convert.py without any changes (namely handle all viewsin one scene). I feel it is probably because of the COLMAP version. However, it seems that changing the --camera argument from OPENCV to SIMPLE_RADIAL in 'convert.py' can also solve this problem, but I am not sure whether doing such is right in the following process. I think I should try COLMAP3.8 or 3.6.

**Comment by kqjt0e11gy0jkgmy** [comment]
Thanks a lot for your reply~ 
I think my problem has been solved~
