### ISSUE TITLE
The use of loss for hard depth and soft depth starts at the moment

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [Fictionarry/DNGaussian#9]
I notice that each data has a different time to start using soft and hard depth loss, is this a big difference? Whether it can be considered that the generality of these losses is not so strong is a result of parameter adjustment

**Comment by Fictionarry** [comment]
Hi, in fact we use the same start times of hard and soft depths (0 and 1000, respectively) for all scenes in LLFF and DTU, containing 8+15 scenes. I think this cross-dataset consistency is sufficient to prove the generality.
